version: 2.1

commands:
  common_test_steps:
    description: Commands to run for every set of tests
    steps:
      - restore_cache:
          key: starwars-server
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          command: ./scripts/install-or-update-starwars-server.sh
          name: Install/Update StarWars Server
      - run:
          command: cd ../starwars-server && npm start
          name: Start StarWars Server
          background: true
      - run:
          command: xcodebuild clean build build-for-testing -workspace "Apollo.xcworkspace" -scheme "${CIRCLE_XCODE_SCHEME}" -sdk "${CIRCLE_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
          name: Clean and build for testing
      - run:
          command: xcodebuild test-without-building -workspace "Apollo.xcworkspace" -scheme "${CIRCLE_XCODE_SCHEME}" -sdk "${CIRCLE_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
          name: Run tests
      - save_cache:
          key: starwars-server
          paths:
            - ../starwars-server


# Important! When adding a new job to `jobs`, make sure to define when it
# executes by also adding it to the `workflows` section below!
jobs:
  macOS10_15:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=macOS,arch=x86_64
      CIRCLE_XCODE_SCHEME: Apollo
      CIRCLE_XCODE_SDK: macosx10.15
    steps:
      - common_test_steps

  iOS13_1:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=13.1,name=iPhone 11
      CIRCLE_XCODE_SCHEME: Apollo
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps

  iOS12_4:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=12.2,name=iPhone XS
      CIRCLE_XCODE_SCHEME: Apollo
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps

  iOS11_4:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=11.4,name=iPhone 8
      CIRCLE_XCODE_SCHEME: Apollo
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps

  tvOS13_0:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=tvOS Simulator,OS=13.0,name=Apple TV
      CIRCLE_XCODE_SCHEME: Apollo
      CIRCLE_XCODE_SDK: appletvsimulator13.0
    steps:
      - common_test_steps

  SQLitemacOS10_15:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=macOS,arch=x86_64
      CIRCLE_XCODE_SCHEME: ApolloSQLite
      CIRCLE_XCODE_SDK: macosx10.15
    steps:
      - common_test_steps

  SQLiteiOS13_1:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=13.1,name=iPhone 11
      CIRCLE_XCODE_SCHEME: ApolloSQLite
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps

  SQLiteiOS12_4:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=12.2,name=iPhone XS
      CIRCLE_XCODE_SCHEME: ApolloSQLite
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps

  SQLiteiOS11_4:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=11.4,name=iPhone 8
      CIRCLE_XCODE_SCHEME: ApolloSQLite
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps

  WebSocketmacOS10_15:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=macOS,arch=x86_64
      CIRCLE_XCODE_SCHEME: ApolloWebSocket
      CIRCLE_XCODE_SDK: macosx10.15
    steps:
      - common_test_steps

  WebSocketiOS13_1:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=13.1,name=iPhone 11
      CIRCLE_XCODE_SCHEME: ApolloWebSocket
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps

  WebSocketiOS12_4:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=12.2,name=iPhone XS
      CIRCLE_XCODE_SCHEME: ApolloWebSocket
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps

  WebSocketiOS11_4:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=iOS Simulator,OS=11.4,name=iPhone 8
      CIRCLE_XCODE_SCHEME: ApolloWebSocket
      CIRCLE_XCODE_SDK: iphonesimulator13.1
    steps:
      - common_test_steps
      
  CodegenLibmacOS10_15:
    macos:
      xcode: "11.1.0"
    environment:
      DESTINATION: platform=macOS,arch=x86_64
      CIRCLE_XCODE_SCHEME: ApolloCodegenLib
      CIRCLE_XCODE_SDK: macosx10.15
    steps:
      - common_test_steps

  CocoaPodsTrunk:
    macos:
      xcode: "11.1.0"
    steps:
      - checkout
      # TODO: Remove when Circle updates the version of CP installed on their
      # image to one that doesn't have https://github.com/CocoaPods/CocoaPods/issues/9176
      - run: pod repo add-cdn trunk 'https://cdn.cocoapods.org/'
      - run: pod trunk push Apollo.podspec
      - run: pod trunk me clean-sessions --all

workflows:
  version: 2
  # This workflow builds and tests the library across various operating systems and versions
  build-and-test:
    jobs:
      - macOS10_15:
          name: Apollo macOS 10.15
      - iOS13_1:
          name: Apollo iOS 13.1
      - iOS12_4:
          name: Apollo iOS 12.4
      - iOS11_4:
          name: Apollo iOS 11.4
      - tvOS13_0:
          name: Apollo tvOS 13.0
      - SQLitemacOS10_15:
          name: ApolloSQLite macOS 10.15
      - SQLiteiOS13_1:
          name: ApolloSQLite iOS 13.1
      - SQLiteiOS12_4:
          name: ApolloSQLite iOS 12.4
      - SQLiteiOS11_4:
          name: ApolloSQLite iOS 11.4
      - WebSocketmacOS10_15:
          name: ApolloWebSocket macOS 10.15
      - WebSocketiOS13_1:
          name: ApolloWebSocket iOS 13.1
      - WebSocketiOS12_4:
          name: ApolloWebSocket iOS 12.4
      - WebSocketiOS11_4:
          name: ApolloWebSocket iOS 11.4
      - CodegenLibmacOS10_15:
          name: Swift Code Generation
      - CocoaPodsTrunk:
          name: Push Podspec to CocoaPods Trunk
          requires:
            - Apollo macOS 10.15
            - Apollo iOS 13.1
            - Apollo iOS 12.4
            - Apollo iOS 11.4
            - Apollo tvOS 13.0
            - ApolloSQLite macOS 10.15
            - ApolloSQLite iOS 13.1
            - ApolloSQLite iOS 12.4
            - ApolloSQLite iOS 11.4
            - ApolloWebSocket macOS 10.15
            - ApolloWebSocket iOS 13.1
            - ApolloWebSocket iOS 12.4
            - ApolloWebSocket iOS 11.4
            - Swift Code Generation
          filters:
            # Only build semver tags
            tags:
              only: /((\d*)\.(\d*)\.(\d*)).*/
            # Don't run this on any branches
            branches:
              ignore: /.*/
